### ISSUE TITLE
bug minning the blocks

### ISSUE THREAD

**Issue by T3rryScary357** [xanthian/VariantVanillaBlocks#4]
the blocks need silk touch to be picked up (the only block affected is the chiseled bookshelf) i'm playing on 1.20.1 with the mod version being 1.3.6

**Comment by xanthian** [comment]
Fabric or Forge?

**Comment by xanthian** [comment]
nm looks like its both versions, i'll sort it today, apologies

**Comment by xanthian** [comment]
This is vanilla behaviour for the Chiseled Bookshelf.

https://minecraft.wiki/w/Chiseled_Bookshelf#Breaking
